SRC = main.c ../lib/graph.c ../lib/priority_queue.c  ../lib/stack.c Prim.c ../lib/union_find.c kruskal.c ../lib/weighted_graph.c ../dac/binary_search.c \
			../sort/quick.c ../sort/utility.c

main: $(SRC)
	cc -g -o main $(SRC)

.PHONY: clean
	
clean:
	rm main 
	rm -r *.dSYM
