# Makefile for sort algorithms
# cc -g -o main main.c merge.c

SRC = main.c insert.c select.c bubble.c utility.c merge.c shell.c quick.c

main: $(SRC)
	cc -g -o main $(SRC)

.PHONY: clean
clean:
	rm main 
	rm -r *.dSYM
